# Official documentation at http://goreleaser.com
project_name: ks
builds:
- env:
    - CGO_ENABLED=0
  id: "ks"
  binary: ks
  goarch:
    - amd64
    - arm64
  goos:
    - windows
    - linux
    - darwin
  hooks:
    post:
      - upx "{{ .Path }}"
  ldflags:
    - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
    - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
    - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
    - -w
dist: bin
archives:
  - name_template: "ks-{{ .Os }}-{{ .Arch }}"
    id: "ks"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: ks
    ids:
      - "ks"
    tap:
      owner: linuxsuren
      name: homebrew-linuxsuren
    folder: Formula
    homepage: "https://github.com/kubesphere-sigs/ks"
    description: ks is a tool which makes it be easy to work with KubeSphere.
    dependencies:
      - name: vim
        type: optional
      - name: bash-completion
        type: optional
      - name: kubectl
        type: optional
    test: |
      version_output = shell_output("#{bin}/ks version")
      assert_match version.to_s, version_output
    install: |
      bin.install name

      prefix.install_metafiles
nfpms:
  - file_name_template: "ks-{{.Os}}-{{.Arch}}"
    id: "ks"
    homepage: https://github.com/kubesphere-sigs/ks
    description: ks is a tool which makes it be easy to work with KubeSphere.
    maintainer: rick <rick@jenkins-zh.cn>
    license: MIT
    vendor: Jenkins
    formats:
      - deb
      - rpm
    recommends:
      - bash-completion
      - vim
      - kubectl
    bindir: /usr/local/bin
    replacements:
      amd64: 64bit
      arm64: arm64
      darwin: macOS
      linux: linux
      windows: windows
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "surenpi/ks:latest"
      - "surenpi/ks:{{.Tag}}"
      - "ghcr.io/linuxsuren/ks/ks:latest"
      - "ghcr.io/linuxsuren/ks/ks:{{.Tag}}"
