apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: kk-config-file
spec:
  hosts:
    - {name: node1, address: {{.address}}, inetnalAddress: {{.address}}}
  roleGroups:
    etcd:
      - node1
    master:
      - node1
    worker:
      - node1
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.19.8
    imageRepo: kubesphere
    clusterName: cluster.local
    containerManager: {{.container}}
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
