apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: ks-pull-request
spec:
  interceptors:
    - ref:
        name: github
      params:
        - name: secretRef
          value:
            secretName: webhook-secret
            secretKey: secret
        - name: eventTypes
          value:
            - pull_request
    - ref:
        name: cel
      params:
        - name: filter
          value: "body.action in ['opened', 'synchronize', 'reopened']"
    - ref:
        name: cel
      params:
        - name: filter
          value: "body.repository.full_name == 'kubesphere-sigs/ks'"
  bindings:
    - ref: pipeline-clusterbinding
      kind: ClusterTriggerBinding
  template:
    ref: ks-pull-request
